[default]
    [default.module_tba]
    enable_module = false
    api_key = "5M2LQFfRJ6rbQf0CklfTf3s4TsiTP7gVhRi448utjbCNFAxyJugdIiCvDDswhKRH"
    matches_update_rate_seconds = 30
    event_update_rate_seconds = 300

    event_key = "2017vapor"